name: Continuous Integration
run-name: ${{ github.actor }} is attempting to integrate their masterpiece ğŸ¤
on:
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ” Running integration for ${{ github.ref }}"
      - name: Checkout repository code ğŸšª
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.13"
          cache: poetry
      - name: Install Dependencies
        run: poetry install
      - name: Type checking ğŸ‘®ğŸ¾â€â™‚ï¸
        run: poetry run mypy .
      - name: Lint with black
        run: poetry run black .
      - name: Run tests
        run: poetry run pytest
      - name: Status ğŸ¤”
        run: echo "This job's status is ${{ job.status }} âœ…"
